default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  host: localhost

development:
  <<: *default
  database: ROR_development

test:
  <<: *default
  database: ROR_test

production:
  <<: *default
  database: ROR_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
